export const ToeicNovel = [
  {
    id: "story-1",
    title: "Khi Tin gặp sếp xin nghỉ làm",
    content:
      "Hôm nay, Tin lên văn phòng gặp sếp xin nghỉ làm. Sếp vô cùng (*) và hỏi vì sao Tin lại (*) như vậy. Tin nói, Tin muốn nghỉ làm để (*) vào (*) riêng của mình. Cứ tưởng Tin sẽ bị phạt vì (*). Bất ngờ thay, sếp không tức giận mà lại (*) và nói sẽ (*) Tin nếu Tin cần. Buổi chiều, Tin đi tìm chủ nhà và (*) hợp đồng thuê nhà. Tin bị (*) phải đóng (*) 6 tháng, tuy nhiên, hiện tại Tin không (*) nên Tin (*) chủ nhà cho thêm 1 ít thời gian. Cuối cùng, 2 (*) cũng (*) và (*). Tin và một số người bạn của mình đang lên (*) về marketing, (*),... Tin biết rằng, (*) là vô cùng quan trọng, (*), Tin đã xem xét việc (*) nhưng vẫn đảm bảo (*) cho (*).",
    words: [
      { en: "surprised", vi: "Ngạc nhiên" },
      { en: "decide", vi: "Quyết định" },
      { en: "focus", vi: "Tập trung" },
      { en: "business", vi: "Kinh doanh" },
      { en: "breach (the contract)", vi: "Phá vỡ hợp đồng" },
      { en: "accept", vi: "Chấp nhận" },
      { en: "support", vi: "Hỗ trợ" },
      { en: "negotiate", vi: "Thương lượng" },
      { en: "obligate", vi: "Bắt buộc" },
      { en: "deposit", vi: "Tiền đặt cọc" },
      { en: "affordable", vi: "Có khả năng chi trả" },
      { en: "convince", vi: "Thuyết phục" },
      { en: "party", vi: "Các bên" },
      { en: "compromise", vi: "Thống nhất" },
      { en: "sign the contract", vi: "Ký hợp đồng" },
      { en: "strategy", vi: "Chiến lược" },
      { en: "product", vi: "Sản phẩm" },
      { en: "customer satisfaction", vi: "Sự hài lòng của khách hàng" },
      { en: "therefore", vi: "Do đó" },
      { en: "lower price", vi: "Giảm giá" },
      { en: "quality", vi: "Chất lượng" },
      { en: "customer", vi: "Khách hàng" },
    ],
  },
  {
    id: "story-2",
    title: "Ngày khai trương",
    content:
      "Hôm nay là ngày (*), sáng nay Tin dậy sớm để (*) mọi thứ cho đâu vào đấy. 1 tuần trước, Tin đã đi phát (*) khắp nơi, (*) trên internet về buổi lễ hôm nay nên hi vọng sẽ (*) nhiều người. Hơn nữa, với (*) của công ty nên hôm nay có nhiều người (*). Nhân dịp khai trương, công ty đưa ra 1 (*), đó là (*) 30% tất cả các sản phẩm nếu khách hàng (*) trong hôm nay. Bởi vì khách hàng thường luôn (*) giá cả khi mua hàng, Tin đã dự trù nhiều dòng sản phẩm (*) để (*) nhu cầu của khách hàng. Ngoài ra, (*) mua hàng hôm nay sẽ được (*). Công ty (*), mọi người (*) tập trung trước sân khấu, Tin (*) một bài (*) về các (*) nếu khách hàng mua hàng tại công ty của Tin. Ai nấy cũng đều (*) cao về (*) của Tin. Đặc biệt, nếu ai (*) (*) sẽ được giảm thêm nữa.",
    words: [
      { en: "grand opening", vi: "Khai trương" },
      { en: "prepare", vi: "chuẩn bị" },
      { en: "brochure", vi: "Sách quảng cáo sản phẩm" },
      { en: "advertise", vi: "quảng cáo" },
      { en: "attract", vi: "thu hút" },
      { en: "convenient location", vi: "địa điểm/vị trí thuận tiện" },
      { en: "well-attended", vi: "có nhiều người tham dự" },
      { en: "special offer", vi: "giảm giá đặc biệt" },
      { en: "discount", vi: "giảm giá" },
      { en: "purchase", vi: "mua" },
      { en: "compare", vi: "so sánh" },
      { en: "various", vi: "đa dạng" },
      { en: "accommodate", vi: "đáp ứng" },
      { en: "those who", vi: "những ai người mà" },
      { en: "free shipping", vi: "miễn phí giao hàng" },
      { en: "announce", vi: "thông báo" },
      { en: "gather", vi: "tập hợp" },
      { en: "address", vi: "phát biểu" },
      { en: "demonstration", vi: "bài chứng minh/thuyết minh" },
      { en: "benefit", vi: "lợi ích" },
      { en: "evaluate", vi: "đánh giá" },
      { en: "speech", vi: "bài nói/bài phát biểu" },
      { en: "apply for", vi: "đăng ký" },
      { en: "membership", vi: "thành viên" },
    ],
  },
  {
    id: "story-3",
    title: "Chuyện ở công ty của Tin",
    content:
      "Hôm nay, Tin (*) một (*) tại (*) của công ty. (*), công ty đang có 1 (*) và 2 (*). Trong cuộc họp này, Tin trình bày (*) và (*) rằng (*) của công ty phải đạt (*) ít nhất 1 triệu đô trong năm nay và sẽ (*) một (*) năm tới. Do vậy, Tin (*) Anna làm (*). Tin rất (*) với Anna về (*) của cô ấy trong buổi (*) vừa rồi. Tin (*) rằng công ty sẽ (*) nếu có Anna (*) sức lực. Nhiệm vụ của Anna không chỉ làm sao để (*) của công ty lên mà còn phải (*) việc tìm ra (*) tốt. Tất nhiên Anna có thể dùng (*) của công ty và nhờ human resources (*) để (*) tìm. Nếu thuận lợi, cuối năm mọi người đều sẽ được tăng (*) và tất nhiên là có (*) để được (*) lên các vị trí khác.",
    words: [
      { en: "hold", vi: "tổ chức" },
      { en: "meeting", vi: "cuộc họp" },
      { en: "headquarters", vi: "trụ sở chính" },
      { en: "Currently", vi: "Hiện tại" },
      { en: "accountant", vi: "kế toán" },
      { en: "technician", vi: "kỹ thuật viên" },
      { en: "plan", vi: "kế hoạch" },
      { en: "determine", vi: "xác định" },
      { en: "goal", vi: "mục tiêu" },
      { en: "revenue", vi: "doanh thu" },
      { en: "establish", vi: "thành lập" },
      { en: "branch", vi: "chi nhánh" },
      { en: "designate", vi: "chỉ định" },
      { en: "head of sales department", vi: "trưởng phòng bán hàng" },
      { en: "impressed", vi: "ấn tượng" },
      { en: "experience", vi: "kinh nghiệm" },
      { en: "interview", vi: "phỏng vấn" },
      { en: "believe", vi: "tin tưởng" },
      { en: "develop", vi: "phát triển" },
      { en: "contribute", vi: "đóng góp" },
      { en: "increase sales", vi: "tăng bán hàng" },
      { en: "responsible for", vi: "chịu trách nhiệm" },
      { en: "supplier", vi: "nhà cung cấp" },
      { en: "budget", vi: "ngân sách" },
      { en: "human resources department", vi: "phòng nhân sự" },
      { en: "support", vi: "hỗ trợ" },
      { en: "salary", vi: "lương" },
      { en: "opportunity", vi: "cơ hội" },
      { en: "promote", vi: "thăng tiến" },
    ],
  },
  {
    id: "story-4",
    title: "Tình hình không ổn",
    content:
      "Tình hình kinh doanh không tốt. Tin đang kêu gọi mọi người đưa ra những (*) để giúp công ty (*). Các (*) nhìn nhau nhưng không ai có (*) gì cả. Tin (*) sẽ có rất nhiều (*), nhưng nếu không (*) thì công ty càng khó khăn hơn. Nguyên nhân phần lớn đến từ các (*) của công ty (*) bị (*) do các máy móc khi Tin mua về đã (*) khiến khách hàng (*) và họ muốn (*) lại. Một số muốn (*) sản phẩm mới, số khác đòi (*). Giải pháp bây giờ là phải (*) lại các máy móc mới, hiện đại hơn. (*), (*) của máy móc (*) mắc nên việc tìm (*) sao cho giá (*) là việc (*) ngay bây giờ. Tin hi vọng (*) 1 tuần, có thể (*) được tình trạng này của (*).",
    words: [
      { en: "initiative", vi: "sáng kiến" },
      { en: "stay competitive", vi: "cạnh tranh" },
      { en: "colleague", vi: "đồng nghiệp" },
      { en: "opinion", vi: "ý kiến" },
      { en: "accept", vi: "chấp nhận" },
      { en: "risk", vi: "rủi ro" },
      { en: "change", vi: "thay đổi" },
      { en: "product", vi: "sản phẩm" },
      { en: "continuously", vi: "liên tục" },
      { en: "defective", vi: "bị lỗi" },
      { en: "outdated", vi: "lỗi thời" },
      { en: "complain", vi: "phàn nàn" },
      { en: "return", vi: "trả lại" },
      { en: "replace", vi: "thay thế" },
      { en: "refund", vi: "hoàn tiền" },
      { en: "invest", vi: "đầu tư" },
      { en: "However", vi: "tuy nhiên" },
      { en: "price", vi: "giá" },
      { en: "relatively", vi: "tương đối" },
      { en: "manufacturer", vi: "nhà sản xuất" },
      { en: "reasonable", vi: "hợp lý" },
      { en: "urgent", vi: "khẩn cấp" },
      { en: "within", vi: "trong vòng" },
      { en: "solve", vi: "giải quyết" },
      { en: "company", vi: "công ty" },
    ],
  },
  {
    id: "story-5",
    title: "Nâng cấp an ninh máy tính ở công ty",
    content:
      "Tin quyết định (*) 20 (*) mới về cho công ty. Nhà cung ứng (*) những máy này sẽ tăng (*) một cách (*) và (*) với những cái (*) hiện tại ở công ty. Ngày mai, (*) sẽ đến và lắp đặt máy tính cũng như (*). Công ty cũng mua thêm (*) để (*) rằng tất cả các (*) quan trọng và (*) không bị mất cắp. Ngay bây giờ, nhân viên cần (*) tất cả (*) quan trọng ra (*) bởi vì ngày mai sẽ không thể (*) máy tính được. Việc làm này sẽ (*) công việc của nhân viên. Sau khi (*) xong, nhân viên cần tham gia buổi (*) hướng dẫn sử dụng và sau đó phải tuân thủ đúng (*). Nếu có bất cứ thắc mắc nào, đừng (*) để (*) phòng (*). (*) sẽ được gửi qua email của mỗi người, khi nhận được, vui lòng (*) là bạn đã nhận được (*).",
    words: [
      { en: "order", vi: "đặt hàng" },
      { en: "computer", vi: "máy tính" },
      { en: "guarantee", vi: "đảm báo" },
      { en: "productivity", vi: "năng suất" },
      { en: "considerably", vi: "đáng kể" },
      { en: "compatible", vi: "tương thích" },
      { en: "printer", vi: " máy in" },
      { en: "technician", vi: "kỹ thuật viên" },
      { en: "network", vi: "hệ thống mạng" },
      { en: "software", vi: "phần mềm" },
      { en: "make sure", vi: "đảm bảo" },
      { en: "document", vi: "tài liệu" },
      { en: "confidential", vi: "bí mật" },
      { en: "copy", vi: "sao chép" },
      { en: "data", vi: "dữ liệu" },
      { en: "disk", vi: "ổ đĩa" },
      { en: "access", vi: "truy cập" },
      { en: "facilitate", vi: "làm cho dễ dàng" },
      { en: "install", vi: "cài đặt" },
      { en: "training session", vi: "buổi họp huấn luyện" },
      { en: "process", vi: "quy trình" },
      { en: "hesitate", vi: "do dự" },
      { en: "contact", vi: "liên hệ" },
      { en: "technical support", vi: "hỗ trợ kỹ thuật" },
      { en: "Detail", vi: "chi tiết" },
      { en: "reply to", vi: "hồi đáp lại" },
      { en: "announcement", vi: "thông báo" },
    ],
  },
  {
    id: "story-6",
    title: "Tuyển nhân viên",
    content:
      "Vì (*) nhân sự để (*) hoạt động, Tin đang (*) 1 (*). Để (*) (*), các (*) phải tải (*) trên công ty. Các bằng cấp được yêu cầu phải được (*) trong đó. Sau đó, các (*) phải (*) online ngược lại. Để (*) người giỏi, công ty đưa ra (*) cũng rất khắt khe vì muốn (*) 1 người có (*) tốt nhất. (*), bạn phải có 2 năm (*). (*) cao, (*), (*) tốt, đồng thời, nếu làm (*), bạn còn sẽ được (*). Tuy nhiên, có thể bạn phải (*) và (*) (*). \nNếu bạn (*), bạn sẽ được mời tham gia (*). (*), bạn sẽ phải (*) 1 buổi đào tạo (*) 7 ngày để hiểu rõ hơn về công ty và công việc của bạn. Bạn được (*) hợp đồng thử việc 2 tháng và được (*) công việc. Đây là giai đoạn rất quan trọng để bạn (*) (*) của bạn. Nếu bạn không làm tốt, rất tiếc, công ty phải (*) bạn. Sau 2 tháng, bạn được ký (*). Ngoài lương, bạn còn được đóng (*). Cuối năm, công ty sẽ có (*) để chọn ra người có (*) nhất và trao (*).",
    words: [
      { en: "lack of", vi: " thiếu" },
      { en: "expand", vi: "mở rộng" },
      { en: "recruit", vi: "tuyển" },
      { en: "supervisor", vi: "người giám sát" },
      { en: "apply for", vi: "nộp đơn" },
      { en: "position", vi: "vị trí" },
      { en: "candidate", vi: "ứng viên" },
      { en: "application form", vi: "mẫu đơn" },
      { en: "enclose/ attach", vi: "đính kèm" },
      { en: "applicant", vi: "ứng viên" },
      { en: "submit", vi: "nộp" },
      { en: "hire", vi: "thuê" },
      { en: "requirement", vi: "yêu cầu" },
      { en: "choose", vi: "chọn" },
      { en: "qualification", vi: "phẩm chất" },
      { en: "At least", vi: "ít nhất" },
      { en: "experience", vi: "kinh nghiệm" },
      { en: "Salary", vi: "lương" },
      { en: "negotiable", vi: "thương lượng" },
      { en: "benefit", vi: "phúc lợi" },
      { en: "work overtime", vi: "làm việc quá giờ" },
      { en: "compensate", vi: "đền bù tiền" },
      { en: "relocate", vi: "chuyển địa điểm" },
      { en: "go on business", vi: "đi công tác" },
      { en: "consistently", vi: "liên tục" },
      { en: "eligible", vi: "có khả năng" },
      { en: "interview", vi: "phỏng vấn" },
      { en: "Shortly thereafter", vi: "ngay sau đó" },
      { en: "take part in", vi: "tham gia" },
      { en: "within", vi: "trong vòng" },
      { en: "sign", vi: "ký" },
      { en: "assign", vi: "phân công" },
      { en: "demonstrate", vi: "chứng minh" },
      { en: "ability", vi: "năng lực" },
      { en: "fire", vi: "sa thải" },
      { en: "permanent contract", vi: "hợp hồng dài hạn" },
      { en: "medical corverage", vi: "bảo hiểm" },
      { en: "performance review", vi: "đánh giá hiệu suất công việc" },
      { en: "contribution", vi: "sự đóng góp" },
      { en: "award", vi: "giải thường" },
    ],
  },
  {
    id: "story-7",
    title: "Quy trình mua hàng ở công ty",
    content:
      "Sản phẩm chất lượng, cùng với các (*) quảng cáo hiệu quả, (*) của công ty Tin càng lớn. (*) ngày càng nhiều nên việc bố trí các (*) sao cho (*) và đảm bảo (*) luôn (*) là điều (*) bây giờ. Khi khách hàng tới cửa hàng tham quan và (*) món hàng cần mua, nhân viên cần phải lịch sự xin tên và số điện thoại để (*) (*). Nếu khách hàng còn đang phân vân thì đưa (*) và (*) khách hàng. Nhân viên phải (*) kỹ trong (*) có còn sản phẩm đó hay không. Nhân viên nhớ (*) khách hàng (*) đúng số điện thoại vì nó sẽ dùng để (*) việc mua hàng trong trường hợp khách hàng làm mất (*). Nếu có bất kỳ (*) nào thì phải sửa ngay. (*) của công ty là tất cả các sản phẩm đều được (*) 1 năm. Nếu sản phẩm có bất kỳ (*) nào, quý khách được (*) lại sảm phẩm mới hoặc được (*) lại. Khách hàng (*) thì sẽ được tính (*), còn không thì phải trả thêm phần (*) (*). Tuỳ thuộc vào khoảng cách mà nhân viên sẽ (*) thời gian giao hàng (*). Thông thường thì khách hàng sẽ (*) sản phẩm (*) vào ngày hôm sau.",
    words: [
      { en: "campaign", vi: "chiến dịch" },
      { en: "reputation", vi: "danh tiếng" },
      { en: "Customer", vi: "khách hàng" },
      { en: "item", vi: "món hàng" },
      { en: "convenient", vi: "thuận tiện" },
      { en: "merchandise", vi: "hàng hoá" },
      { en: "available", vi: "có sẵn" },
      { en: "crucial", vi: "quan trọng" },
      { en: "decide", vi: "quyết định" },
      { en: "fulfill", vi: "hoàn thành" },
      { en: "order", vi: "đơn hàng" },
      { en: "catalog", vi: "danh mục sản phẩm" },
      { en: "consult", vi: "tư vấn" },
      { en: "check", vi: "kiểm tra" },
      { en: "warehouse", vi: "nhà kho" },
      { en: "remind", vi: "nhắc nhở" },
      { en: "provide", vi: "cung cấp" },
      { en: "verify", vi: "xác nhận" },
      { en: "invoice/receipt", vi: "hoá đơn" },
      { en: "mistake", vi: "lỗi" },
      { en: "Policy", vi: "chính sách" },
      { en: "warranty", vi: "bảo hành" },
      { en: "defective", vi: "lỗi (sản phẩm bị lỗi)" },
      { en: "replace", vi: "thay thế" },
      { en: "refund", vi: "hoàn tiền" },
      { en: "buy in bulk", vi: "mua số lượng lớn" },
      { en: "no extra cost", vi: "không tính thêm phí" },
      { en: "delivery", vi: "giao hàng" },
      { en: "charge", vi: "tiền phí" },
      { en: "estimate", vi: "ước tính" },
      { en: "accurately", vi: "chính xác" },
      { en: "receive", vi: "nhận" },
      { en: "promptly", vi: "ngay lập tức" },
    ],
  },
  {
    id: "story-8",
    title: "Đầu tư",
    content:
      "Hôm nay, Tin ghé qua (*) để (*) (*) ngân hàng của công ty để thực hiện các (*) dễ dàng với khách hàng hơn. (*) nói Tin phải cung cấp (*) và điền vào mẫu đơn. Tin đọc (*) các mục rồi sau đó ký (*). Với những (*), bây giờ khách hàng có thể chuyển khoản trực tiếp (*) tài khoản của công ty mà không cần phải đến cửa hàng. Theo như (*) của Tin, việc này sẽ giúp cho bộ phận (*) bớt đi áp lực công việc. Trong lúc ngồi chờ, Tin nghĩ, nếu sau này mình có nhiều tiền, Tin sẽ là 1 (*). Tin sẽ tìm những công ty phát triển ổn định để đầu tư (*). Ngoài ra, Tin cũng sẽ đầu tư vào (*), Tin (*) lựa chọn những (*) gần (*) để dễ cho thuê. Nếu cần, Tin sẽ (*) căn nhà lại cho phù hợp với nhu cầu của khách hàng. Vì có quá nhiều (*) trên thị trường nên Tin phải cung cấp (*) với (*) cho khách hàng, thì mới (*) được nhiều người thuê.",
    words: [
      { en: "bank", vi: "ngân hàng" },
      { en: "activate", vi: "kích hoạt" },
      { en: "account", vi: "tài khoản" },
      { en: "transaction", vi: "giao dịch" },
      { en: "Cashier", vi: "thu ngân" },
      { en: "identification", vi: "chứng minh nhân dân" },
      { en: "carefully", vi: "một cách cẩn thân" },
      { en: "signature", vi: "chữ ký" },
      { en: "outstanding bil", vi: "hoá đơn chưa thanh toán" },
      { en: "through", vi: "thông qua" },
      { en: "forecast", vi: "dự đoán" },
      { en: "accounting", vi: "kế toán" },
      { en: "investor", vi: "nhà đầu tư" },
      { en: "long-term", vi: "dài hạn" },
      { en: "real estate", vi: "bất động sản" },
      { en: "intend to", vi: "dự định làm gì" },
      { en: "aparment", vi: "căn hộ" },
      { en: "public transportation", vi: "phương tiện công cộng" },
      { en: "customize", vi: "điều chỉnh cho phù hợp" },
      { en: "competitor", vi: "đối thủ" },
      { en: "excellent service", vi: "dịch vụ xuất sắc" },
      { en: "reasonable price", vi: "giá cả hợp lý" },
      { en: "attract", vi: "thu hút" },
    ],
  },
  {
    id: "story-9",
    title: "Đăng ký tạp chí",
    content:
      "(*) TPA là tạp chí (*) về lĩnh vực (*). Tin đã (*) tạp chí này được 2 tháng. Các (*) của nó (*) 2 tuần 1 lần, cung cấp những kiến thức rất bổ ích cho những người mới kinh doanh như Tin. Hôm nay, nhân dịp (*) 10 năm của TPA, nếu ai đăng ký 1 năm sẽ được nhận được (*) giảm 50%. Những ai đăng ký mà đã (*), nếu (*) lại thì được tặng thêm 1 tháng nhận báo miễn phí. Tại buổi lễ, TPA mời đến 1 (*) nổi tiếng, với cuốn sách (*) NHÀ KHỞI NGHIỆP THÔNG MINH. Tại đây, anh sẽ chia sẻ kinh nghiệm xương máu mà anh đã trải qua, từ việc xuất phát điểm là 1 (*), thi đấu thất bại trong 3 năm (*), (*) gặp tai nạn nặng đến mức (*) được (*) cho đến (*) thành công của ngày hôm nay. Bài chia sẻ của anh sẽ (*) trong 30 phút. Sau đó, anh sẽ trả lời những câu hỏi của (*). Cũng trong dịp này, buổi ký tặng sách sẽ được tiến hành. Toàn bộ chi phí sẽ do TPA (*), số tiền thu được từ việc bán sách sẽ được (*) để gây (*). (*) tham gia thì miễn phí. Tuy nhiên, về (*) chỉ có 100 chỗ ngồi nên những ai xác định tham gia nên đăng ký giữ chỗ (*).",
    words: [
      { en: "Magazine", vi: "tạp chí" },
      { en: "famous", vi: "nổi tiếng" },
      { en: "business", vi: "kinh doanh" },
      { en: "subscribe", vi: "đăng ký" },
      { en: "issue", vi: "ấn bản" },
      { en: "publish", vi: "xuát bản" },
      { en: "celebrate", vi: "kỷ niệm" },
      { en: "voucher", vi: "phiếu quà tặng" },
      { en: "expire", vi: "hết hạn" },
      { en: "renew", vi: "gia hạn" },
      { en: "author", vi: "tác giả" },
      { en: "best seller", vi: "bán chạy nhất (Sách)" },
      { en: "athlete", vi: "vận động viên" },
      { en: "consecutive", vi: "liên tiếp" },
      { en: "unfortunately", vi: "không may" },
      { en: "discontinue", vi: "không tiếp tục" },
      { en: "career", vi: "sự nghiệp" },
      { en: "achievement", vi: "thành tựu" },
      { en: "take place", vi: "diễn ra" },
      { en: "audience", vi: "khán giả" },
      { en: "donate", vi: "tài trợ" },
      { en: "contribute", vi: "đóng góp" },
      { en: "charity fund", vi: "quỹ từ thiện" },
      { en: "Admission", vi: "sự cho phép đi vào" },
      { en: "capacity", vi: "sức chứa" },
      { en: "in advance", vi: "trước" },
    ],
  },
  {
    id: "story-10",
    title: "Du lịch công ty",
    content:
      "Sau 6 tháng hoạt động, với sự nỗ lực hết mình, công ty của Tin đã đạt được doanh thu (*). Dưới đây là email của công ty du lịch Apax gửi cho Tin: “Apax là công ty (*) tổ chức du lịch. Hơn 5 năm qua, chúng tôi đã trở thành đơn vị (*) nếu quý công ty muốn tổ chức các (*) gắn kết tập thể công ty. Nếu quý công ty đăng ký (*) thì sẽ được giảm 10% tiền phòng khách sạn. Apax sẽ (*) cho công ty dựa trên số lượng người mà công ty cung cấp. Đồng thời, (*) vào các khu vui chơi sẽ giảm 15%. Đây là (*) chung của công ty, ngay cả trong trường hợp quý khách (*), hãy cứ gửi cho chúng tôi (*), chúng tôi sẽ (*) lên cấp trên. Nếu nhận được (*), chúng tôi sẽ (*) quý khách ngay. Quý khách có thể (*) bằng cách (*) email này hoặc đến trực tiếp (*) của chúng tôi. Tuy nhiên, (*) đang (*) nên quý khách vui lòng đậu xe ở toà nhà bên cạnh. Khi kết thúc tour, chúng tôi sẽ (*) 1 (*). Quý khách sẽ nhận được (*). Chúng tôi luôn lắng nghe (*) của quý khách. Hãy yên tâm vì phản hồi của quý vị sẽ được (*). Xin cảm ơn.”",
    words: [
      { en: "as planned", vi: "theo như kế hoạch" },
      { en: "specialize in", vi: "chuyên làm lĩnh vực nào đó" },
      { en: "reliable/dependable", vi: "đáng tin cậy" },
      { en: "outdoor activities", vi: "hoạt động ngoài trời" },
      { en: "guided tour", vi: "tour du lịch có hướng dẫn" },
      { en: "make a reservation", vi: "đặt phòng" },
      { en: "ticket", vi: "vé" },
      { en: "policy", vi: "chính sách" },
      { en: "tight budget", vi: "ngân sách eo hẹp" },
      { en: "proposal", vi: "bản đề xuất" },
      { en: "present", vi: "trình bày" },
      { en: "approval", vi: "sự đồng ý" },
      { en: "notify", vi: "thông báo" },
      { en: "register", vi: "đăng ký" },
      { en: "reply to", vi: "phản hồi" },
      { en: "office", vi: "văn phòng" },
      { en: "parking lot", vi: "bãi đậu xe" },
      { en: "under construction", vi: "đang xây dựng" },
      { en: "conduct", vi: "tiến hành" },
      { en: "survey", vi: "khảo sát" },
      { en: "questionnaire", vi: "bảng câu hỏi" },
      { en: "feedback", vi: "phản hồi" },
      { en: "strictly confidential", vi: "bí mật tuyệt đối" },
    ],
  },
  {
    id: "story-11",
    title: "Mở rộng kinh doanh",
    content:
      "Sau 1 năm ổn định và phát triển, (*) tại (*) đã cũ, Tin quyết định (*) lại. Một số (*) cũng phải mua lại. Việc này có thể gây (*) cho nhân viên. Vì thế, trong tuần này, nhân viên sẽ (*) lịch làm việc của mình, làm trễ hơn và về trễ hơn. Công ty sẽ (*) tiền để (*) nhân viên làm việc. Những người thợ sửa văn phòng sẽ cố gắng hoàn thành (*), hoặc (*). Trường hợp (*) không ai (*) cả, vì nó sẽ phát sinh thêm rất nhiều (*). Sau khi sửa chữa, công ty sẽ (*) các (*) mới, nên hiện tại đang (*) những (*) kể cả trong công ty và bên ngoài để (*). \nỨng viên phải có (*) và (*) sản xuất, có thể (*) và (*) (*). Nhiệm vụ chính là (*) quy trình sản xuất không bị (*). Vị trí này đòi hỏi khả năng làm việc (*) cũng như (*). Đừng lo vì bạn sẽ có cấp trên (*). Tất nhiên, bạn phải (*) hướng dẫn của cấp trên. Nếu bạn đang (*) 1 (*) để phát triển bản thân và nhận thấy mình sẽ là một nhân viên (*) thì đây là vị trí vô cùng phù hợp với bạn. (*), bạn (*) kèm với (*) của bạn và (*) cho công ty.",
    words: [
      { en: "facility", vi: "cơ sở vật chất" },
      { en: "headquarters", vi: "trụ sở chính" },
      { en: "renovate", vi: "tân trang lại" },
      { en: "office supplies", vi: "thiết bị văn phòng" },
      { en: "interrupt", vi: "gián đoạn" },
      { en: "reschedule", vi: "dời lại lịch" },
      { en: "reimburse", vi: "đền bù, trả lại (tiền)" },
      { en: "encourage", vi: "khuyến khích" },
      { en: "on schedule", vi: "đúng lịch trình" },
      { en: "ahead of schedule", vi: "trước lịch trình" },
      { en: "behind schedule", vi: "trễ hạn" },
      { en: "expect", vi: "mong đợi" },
      { en: "expense", vi: "chi phí" },
      { en: "implement", vi: "tiến hành" },
      { en: "project", vi: "dự án" },
      { en: "seek", vi: "tìm kiếm" },
      { en: "potential individual", vi: "cá nhân tiềm năng" },
      { en: "fill the vacant position", vi: "lấp đầy vị trí trống" },
      { en: "comprehensive knowledge of", vi: "sự hiểu biết toàn diện với" },
      { en: "familiarity with", vi: "sự quen biết với" },
      { en: "figure out", vi: "tìm ra" },
      { en: "handle problem", vi: "giải quyết vấn đề" },
      { en: "in a timely manner", vi: "kịp thời" },
      { en: "in charge of", vi: "chịu trách nhiệm" },
      { en: "error", vi: "lỗi" },
      { en: "collaboratively", vi: "hợp tác" },
      { en: "independently", vi: "độc lập" },
      { en: "instruct", vi: "hướng dẫn" },
      { en: "comply with/abide by/ adhere to", vi: "tuân thủ" },
      { en: "look for", vi: "tìm kiếm" },
      { en: "opportunity", vi: "cơ hội" },
      { en: "potential", vi: "tiềm năng" },
      { en: "Simply", vi: "đơn giản" },
      { en: "fill out a form", vi: "điền vào mẫu" },
      { en: "résumé", vi: "hồ sơ" },
      { en: "hand in", vi: "nộp (trao trực tiếp bằng tay)" },
    ],
  },
  {
    id: "story-12",
    title: "Ra mắt sản phẩm mới",
    content:
      "Công ty Betin là (*) của Tin (*) 1 (*) để quảng bá về sản phẩm mới nhất cuả họ. Đây là (*) lớn, có đến 10 (*) và (*). Họ còn (*) thêm 5 (*). (*) của công ty đã gọi điện, gửi (*) cho nhiều đối tác, kể cả các đối tác (*). Để việc (*) sản phẩm này thành công, chính (*) của công ty sẽ (*) về (*) của sản phẩm trước các (*) của các công ty tham gia. Sản phẩm này (*) khách hàng tiến hành việc kinh doanh trôi chảy hơn. Chủ tịch (*) sản phẩm sẽ (*) (*) của những công ty tham dự, bởi vì các (*) trước đây đã nhận được rất nhiều (*) (*). Giá sản phẩm cũng (*) hợp lý vì chỉ (*) 1000$. Họ (*) mục tiêu sẽ ký kết được hợp đồng ngay tại ngày hôm đó, vì (*) của hợp đồng họ cũng đã gửi trước đó cho khách hàng tham khảo. Tất nhiên chỉ cần đặt cọc trước, còn (*) đủ thì không nhất thiết.",
    words: [
      { en: "partner", vi: "đối tác" },
      { en: "organize", vi: "tổ chức" },
      { en: "seminar/workshop", vi: "hội thảo" },
      { en: "event", vi: "sự kiện" },
      { en: "secretary", vi: "thư ký" },
      { en: "receptionist", vi: "lễ tân" },
      { en: "hire", vi: "thuê" },
      { en: "assistant", vi: "trợ lý" },
      { en: "Executive", vi: "chuyên gia cấp cao" },
      { en: "invitation", vi: "thư mời" },
      { en: "international", vi: "quốc tế" },
      { en: "launch/release", vi: "tung ra" },
      { en: "president", vi: "chủ tịch" },
      { en: "present", vi: "trình bày" },
      { en: "feature", vi: "đặc điểm" },
      { en: "representative", vi: "người đại diện" },
      { en: "allow", vi: "cho phép" },
      { en: "commit", vi: "cam kết" },
      { en: "meet/accommodate", vi: "đáp ứng" },
      { en: "need", vi: "nhu cầu" },
      { en: "version", vi: "phiên bản" },
      { en: "reflect", vi: "phản ánh" },
      { en: "positive", vi: "tích cực" },
      { en: "extremely", vi: "rất" },
      { en: "approximately", vi: "xấp xỉ" },
      { en: "determine", vi: "xác định" },
      { en: "terms and conditions", vi: "điều khoản hợp đồng" },
      { en: "payment", vi: "thanh toán" },
    ],
  },
  {
    id: "story-13",
    title: "Hãng hàng không V-Airline",
    content:
      "(*), những người trẻ tuổi (*) du lịch bụi, duy chuyển bằng xe máy tới những (*) mà họ (*) chi trả hơn là các phương tiện cao cấp, (*) là (*) vì giá quá mắc và rất hay bị (*). Hoạt động của hãng hàng không V-Airline cũng bị ảnh hưởng khá nhiều, vì thế công ty (*) ý tưởng chuyển sang kinh doanh vé máy bay giá rẻ để tăng (*) duy chuyển bằng (*). Với chính sách (*), V-Airline đã (*) được những (*) so với đối thủ và nhanh chóng trở thành (*). Với (*) là giá (*), chỉ sau 2 năm hoạt động, V-Airline đã giành được hầu hết (*). Đến nỗi, (*) của công ty cũng vươn ra quốc tế. Việc (*) (*) của hãng sao cho giá luôn rẻ yêu cầu phải (*) rất nhiều. Do vậy mà các (*) cao cấp cũng bị (*). Tuy nhiên, công ty luôn luôn đặt (*) làm (*) của mình.",
    words: [
      { en: "Recently", vi: "" },
      { en: "have a tendency to", vi: "" },
      { en: "destination", vi: "" },
      { en: "capable of", vi: "" },
      { en: "especially", vi: "" },
      { en: "flight", vi: "" },
      { en: "delay/postpone", vi: "" },
      { en: "come up with", vi: "" },
      { en: "demand", vi: "" },
      { en: "plane", vi: "" },
      { en: "reasonable price/rate", vi: "" },
      { en: "obtain", vi: "" },
      { en: "outstanding accomplishment", vi: "" },
      { en: "leading firm", vi: "" },
      { en: "advantage", vi: "" },
      { en: "competitive", vi: "" },
      { en: "market share", vi: "" },
      { en: "reputation", vi: "" },
      { en: "maintain", vi: "" },
      { en: "operation", vi: "" },
      { en: "cut cost", vi: "" },
      { en: "service", vi: "" },
      { en: "restricted", vi: "" },
      { en: "customer satisfaction", vi: "" },
      { en: "priority", vi: "" },
    ],
  },
  {
    id: "story-14",
    title: "Sách dạy nấu ăn",
    content:
      "Nhà hàng Beerant vừa kết hợp với (*) nổi tiếng, ông Michel để tung ra 1 cuốn sách về nấu ăn (*), (*), chưa từng có trên thị trường. Bộ sách vừa được tung ra (*) thì đã có 1000 người đặt mua. Những bà nội trợ (*) sự khác biệt (*) của bộ (*) này so với các quyển sách khác hiện có trên thị trường. Vì nó (*) các bí quyết nấu ăn mà các cuốn sách khác thường dấu diếm. Đầu bếp Michel đã đi vòng quanh thế giới để (*) và (*) các (*) nấu ăn trong 1 năm trước khi viết thành sách. Cuốn sách này giúp người đọc (*) việc lãng phí thời gian và tiền bạc để đăng ký 1 khoá học nấu ăn. (*) của các món ăn (*) nhiều, hướng dẫn khá (*) nên hầu như chỉ cần áp dụng đúng công thức là sẽ có được một (*) (*) ngay. Tát nhiên, ngày ra mắt sách, ông Machel có (*) và làm mẫu một vài món ăn. Ai cũng (*) xem ông thể hiện tài năng của mình. Việc này (*) 1 tiếng (*) 30 phút như dự định.",
    words: [
      { en: "chef", vi: "" },
      { en: "exclusive", vi: "" },
      { en: "unique", vi: "" },
      { en: "officially", vi: "" },
      { en: "recognize", vi: "" },
      { en: "obviously", vi: "" },
      { en: "document", vi: "" },
      { en: "disclose/reveal", vi: "" },
      { en: "assess/evaluate", vi: "" },
      { en: "assemble", vi: "" },
      { en: "recipe", vi: "" },
      { en: "avoid", vi: "" },
      { en: "Variety", vi: "" },
      { en: "relatively", vi: "" },
      { en: "specific", vi: "" },
      { en: "delicious", vi: "" },
      { en: "dish", vi: "" },
      { en: "particiapate in", vi: "" },
      { en: "tobe eager to", vi: "" },
      { en: "last", vi: "" },
      { en: "instead of", vi: "" },
    ],
  },
  {
    id: "story-15",
    title: "Tiệm bánh mỳ nổi tiếng",
    content:
      "Theo cuộc (*) gần đây của local (*), (*) ABC đứng đầu về (*) và đạt được (*) nhiều nhất so với các tiệm bánh khác. Để có được (*) (*), tiệm bánh đã luôn (*) để tạo ra những chiếc bánh (*) nhất. Không những thế, ABC còn có dịch vụ (*) cho (*) đến nỗi bánh tới tay người dùng vẫn còn nóng như vừa mới ra lò. Nếu bánh bị (*) trong quá trình giao, (*) sẽ (*) (*) và (*) đổi bánh mới ngay. Tất cả các nhân viên giao hàng đều có (*) (*). Hiện tại, sắp tới Valentine, ABC đưa ra chương trình ưu đãi, mua từ 5 bánh sẽ được 1 cặp (*) (*) xem (*) vào cuối tuần này. Nếu gia đình có con dưới 5 tuổi thì bé sẽ (*) vé, (*) phải (*) bố mẹ.",
    words: [
      { en: "survey", vi: "" },
      { en: "local community", vi: "" },
      { en: "bakery", vi: "" },
      { en: "popularity", vi: "" },
      { en: "profit", vi: "" },
      { en: "significant", vi: "" },
      { en: "achievement", vi: "" },
      { en: "make efforts", vi: "" },
      { en: "quality", vi: "" },
      { en: "delivery", vi: "" },
      { en: "recipient", vi: "" },
      { en: "damage", vi: "" },
      { en: "staff", vi: "" },
      { en: "immediately", vi: "" },
      { en: "verify", vi: "" },
      { en: "carry out", vi: "" },
      { en: "driver’s license", vi: "" },
      { en: "valid", vi: "" },
      { en: "complimentary", vi: "" },
      { en: "ticket", vi: "" },
      { en: "concert", vi: "" },
      { en: "tobe exempt from", vi: "" },
      { en: "as long as", vi: "" },
      { en: "accompanied by", vi: "" },
    ],
  },
  {
    id: "story-16",
    title: "Thư mời tham gia buổi tiệc",
    content:
      "Nhằm ghi nhận sự (*) của (*), công ty gửi đến toàn bộ nhân viên email lần thứ 2 như là (*) để tham gia buổi tiệc (*) kỷ niệm 10 năm công ty hoạt động. (*) sẽ được (*) ở nhà hàng White Palace, (*) VPT bank. Sau 1 tháng (*) quá trình (*), nhà hàng đã có (*). Đồng thời (*) cũng (*) hơn rất nhiều. Vấn đề bây giờ là bạn phải xác nhận có tham gia hay không để chúng tôi biết chắc (*) của (*) để (*). (*) bạn có tham gia thì cũng phải phản hồi lại email cho chúng tôi. Lưu ý, bữa tiệc này (*) tất cả nhân viên, kể cả nhân viên (*). Bạn sẽ nhận (*) (*) 20 tháng này. Chúng tôi (*) tới tất cả các bạn, và rất hi vọng rằng nhìn thấy các bạn ở ngày hôm đó. \nĐặc biệt, công ty sẽ vinh danh Pak, cũng là người sắp (*) vào tháng tới, người đã gắn bó cùng với công ty 30 năm qua.",
    words: [
      { en: "dedication", vi: "" },
      { en: "employee", vi: "" },
      { en: "reminder", vi: "" },
      { en: "anniversary", vi: "" },
      { en: "Ceremony", vi: "" },
      { en: "hold", vi: "" },
      { en: "adjacent to", vi: "" },
      { en: "undergo", vi: "" },
      { en: "renovation", vi: "" },
      { en: "spacious interior", vi: "" },
      { en: "design", vi: "" },
      { en: "innovate", vi: "" },
      { en: "number", vi: "" },
      { en: "attendee", vi: "" },
      { en: "book table", vi: "" },
      { en: "Whether or not", vi: "" },
      { en: "intend for", vi: "" },
      { en: "temporary", vi: "" },
      { en: "advance ticket", vi: "" },
      { en: "prior to", vi: "" },
      { en: "extend our sincere thanks", vi: "" },
      { en: "retire", vi: "" },
    ],
  },
  {
    id: "story-17",
    title: "Ngày cuối tuần",
    content:
      "Hôm nay là cuối tuần, Tin thật sự muốn đi đâu đó để giảm cằn thẳng vì nguyên cả tuần rồi Tin tin có đến 3 (*) và phải chạy để không bị (*). Tin muốn đi (*), nhưng mà (*) cuối tuần này cũng đang có (*) đến 30% nên Tin đang phân vân. Tin rủ những người bạn của mình thì họ lại muốn đi đến trung tâm thương mại Vincom mới mở. Vì ở đó sẽ có rất nhiều loại hình (*) nên sẽ vui lắm. Tin đồng ý. Để (*) (*) nhiều hơn, Vincon đã treo băng rôn quảng cáo khá lớn và phát (*) trước đó cả tuần. Tới nơi, cả nhóm vô cùng (*) bởi (*) của toà nhà. Từ (*) cho đến đèn trang trí, nội thất,... quá hoàn hảo. Họ quả thật là (*) trong việc chinh phục khách hàng. Đúng là không phụ lòng (*) của khách hàng, cũng không không (*) sai sự thật. Ngày nay, ngoài việc ăn no qua, thì việc mặc đẹp, mặc (*) và (*) có giá (*) là những điều không thể bỏ qua. Tin và bạn đi vào khu vực trò chơi thì may mắn (*) mà nhận được 1 (*) trị giá là 1 (*) 2 ngày 3 đêm lại Đà Lạt, cùng với (*) tất cả bữa ăn. Cả nhóm vô cùng mãn nguyện.",
    words: [
      { en: "project", vi: "" },
      { en: "behind schedule", vi: "" },
      { en: "museum", vi: "" },
      { en: "concert", vi: "" },
      { en: "discount", vi: "" },
      { en: "entertainment", vi: "" },
      { en: "attract", vi: "" },
      { en: "customer", vi: "" },
      { en: "brochure", vi: "" },
      { en: "impressed", vi: "" },
      { en: "design", vi: "" },
      { en: "elevator", vi: "" },
      { en: "expert", vi: "" },
      { en: "expect", vi: "" },
      { en: "advertise", vi: "" },
      { en: "durable", vi: "" },
      { en: "items", vi: "" },
      { en: "reasonable", vi: "" },
      { en: "fill out a form", vi: "" },
      { en: "voucher", vi: "" },
      { en: "vacation", vi: "" },
      { en: "complimentary", vi: "" },
    ],
  },
  {
    id: "story-18",
    title: "Một ngày tồi tệ",
    content:
      "Hôm nay Tin phải (*) ở Acex (*). Tin (*) vé máy bay khứ hồi trước đó 2 tuần. Đồng thời cũng đã đặt (*) khách sạn. Khi Tin ra sân bay thì lại nhận được (*) là máy bay bị (*) lại hôm sau mới đi, vì lý do (*). Tin rất lo lắng vì sợ trễ công tác. Tin đổi vé máy bay thì nhân viên hướng dẫn Tin (*) cổng số 7 để làm (*). Khi tới nơi, nhân viên nói rằng (*) tất cả các chuyến bay đều đã được đặt vé sạch. Vậy là không còn (*) nào khác, Tin đành lỡ hội nghị và phải (*) đối tác xin lỗi. Điều này cũng có nghĩa là những (*) Tin (*) sẽ không còn ý nghĩa gì nữa. Tin gọi cho khách sạn xem có lấy lại được tiền không thì (*) cũng không được. Đây là lần thứ 2 (*) Tin đi máy bay hãng này và gặp (*) hoài. Tin (*) về việc có nên bay hãng này nữa hay không.",
    words: [
      { en: "go on business", vi: "" },
      { en: "conference center", vi: "" },
      { en: "book", vi: "" },
      { en: "reservation", vi: "" },
      { en: "announcement", vi: "" },
      { en: "postpone", vi: "" },
      { en: "bad weather", vi: "" },
      { en: "proceed to", vi: "" },
      { en: "procedure", vi: "" },
      { en: "currently", vi: "" },
      { en: "choice", vi: "" },
      { en: "contact", vi: "" },
      { en: "document", vi: "" },
      { en: "prepare", vi: "" },
      { en: "result", vi: "" },
      { en: "consecutive", vi: "" },
      { en: "trouble", vi: "" },
      { en: "consider", vi: "" },
    ],
  },
  {
    id: "story-19",
    title: "Thư mời dự họp",
    content:
      "Anh ngữ Benzen (*) tất cả các khách hàng và nhân viên (*) về việc quan trọng sau đây. (*) 5 năm hoạt động và (*), BenzenEnglish chính thức (*) và được (*) tại Thủ Đức. Lễ khai trương sẽ được take (*) vào đầu tuần sau. Riêng cuối tuần này, các (*) sẽ có 1 cuộc (*) để nắm bắt rõ về vấn đề này. Mong các bạn (*). Không vắng (*). Để đảm bảo cuộc họp (*) và (*), vui lòng đọc kỹ (*) được (*) trong email này. Cuộc họp được (*) trong thời gian kéo dài 30 phút thay vì 1 tiếng (*). (*) của bạn là rất quan trọng, tuy nhiên, cũng nhớ rằng, trong cuộc họp có nhiều thông tin (*) nên vui lòng không (*) ra ngoài. Anh Tin sẽ (*) cuộc họp này nên có gì cần cứ liên hệ anh ấy. Về phía khách hàng, (*) việc tri ân, Benzen sẽ có những (*) xinh xắn vào ngày hôm đó cho các bạn.",
    words: [
      { en: "announce", vi: "" },
      { en: "company", vi: "" },
      { en: "Over", vi: "" },
      { en: "develop", vi: "" },
      { en: "establish", vi: "" },
      { en: "locate", vi: "" },
      { en: "take place", vi: "" },
      { en: "division", vi: "" },
      { en: "meeting", vi: "" },
      { en: "keep an appointment", vi: "" },
      { en: "under any circumstances", vi: "" },
      { en: "brief", vi: "" },
      { en: "productive", vi: "" },
      { en: "detail", vi: "" },
      { en: "attach", vi: "" },
      { en: "expected", vi: "" },
      { en: "as planned", vi: "" },
      { en: "Presence", vi: "" },
      { en: "confidential", vi: "" },
      { en: "disclose", vi: "" },
      { en: "in charge of", vi: "" },
      { en: "as part of", vi: "" },
      { en: "gift", vi: "" },
    ],
  },
  {
    id: "story-20",
    title: "Bộ từ vựng TOEIC độc quyền",
    content:
      "BenzenEnglish vừa tung ra bộ tài liệu học TOEIC kiểu mới, được (*) công phu, (*) và (*) trên (*) hiện nay. Bộ truyện được (*) ra (*) 2 tuần (*). Người học có thể (*) sự khác biệt (*) so với các (*). Chính người sáng lập trung tâm đã giành thời gian (*) khả năng của mình để sáng tạo nên, đồng thời (*) lại cho phù hợp với cách học và (*) của học sinh Việt Nam. Bộ truyện tỉnh lượt phần phiên âm để (*) sự phức tạp, các bạn có thể tìm thấy nguồn tra ở phần hướng dẫn. 20 câu chuyện chứa (*), (*) (*) những từ vựng (*) cho cấp độ 550 TOEIC. Rất hi vọng bộ truyện này sẽ giúp các bạn học từ vựng TOEIC nhanh chóng, dễ thuộc và đạt được kết quả thật tốt.",
    words: [
      { en: "compose", vi: "" },
      { en: "exclusive", vi: "" },
      { en: "unique", vi: "" },
      { en: "market", vi: "" },
      { en: "launch", vi: "" },
      { en: "prior to", vi: "" },
      { en: "as anticipated", vi: "" },
      { en: "figure out", vi: "" },
      { en: "obviously", vi: "" },
      { en: "competitor", vi: "" },
      { en: "contribute", vi: "" },
      { en: "customize", vi: "" },
      { en: "ability", vi: "" },
      { en: "avoid", vi: "" },
      { en: "variety", vi: "" },
      { en: "relatively", vi: "" },
      { en: "sufficient", vi: "" },
      { en: "essential", vi: "" },
    ],
  },
];
