export const ToeicNovel = [
  {
    id: "story-1",
    title: "Khi Tin gặp sếp xin nghỉ làm",
    content:
      "Hôm nay, Tin lên văn phòng gặp sếp xin nghỉ làm. Sếp vô cùng (*) và hỏi vì sao Tin lại (*) như vậy. Tin nói, Tin muốn nghỉ làm để (*) vào (*) riêng của mình. Cứ tưởng Tin sẽ bị phạt vì (*). Bất ngờ thay, sếp không tức giận mà lại (*) và nói sẽ (*) Tin nếu Tin cần. Buổi chiều, Tin đi tìm chủ nhà và (*) hợp đồng thuê nhà. Tin bị (*) phải đóng (*) 6 tháng, tuy nhiên, hiện tại Tin không (*) nên Tin (*) chủ nhà cho thêm 1 ít thời gian. Cuối cùng, 2 (*) cũng (*) và (*). Tin và một số người bạn của mình đang lên (*) về marketing, (*),... Tin biết rằng, (*) là vô cùng quan trọng, (*), Tin đã xem xét việc (*) nhưng vẫn đảm bảo (*) cho (*).",
    words: [
      "surprised",
      "decide",
      "focus",
      "business",
      "breach (the contract)",
      "accept",
      "support",
      "negotiate",
      "obligate",
      "deposit",
      "affordable",
      "convince",
      "party",
      "compromise",
      "sign the contract",
      "strategy",
      "product",
      "customer satisfaction",
      "therefore",
      "lower price",
      "quality",
      "customer",
    ],
  },
  {
    id: "story-2",
    title: "Ngày khai trương",
    content:
      "Hôm nay là ngày (*), sáng nay Tin dậy sớm để (*) mọi thứ cho đâu vào đấy. 1 tuần trước, Tin đã đi phát (*) khắp nơi, (*) trên internet về buổi lễ hôm nay nên hi vọng sẽ (*) nhiều người. Hơn nữa, với (*) của công ty nên hôm nay có nhiều người (*). Nhân dịp khai trương, công ty đưa ra 1 (*), đó là (*) 30% tất cả các sản phẩm nếu khách hàng (*) trong hôm nay. Bởi vì khách hàng thường luôn (*) giá cả khi mua hàng, Tin đã dự trù nhiều dòng sản phẩm (*) để (*) nhu cầu của khách hàng. Ngoài ra, (*) mua hàng hôm nay sẽ được (*). Công ty (*), mọi người (*) tập trung trước sân khấu, Tin (*) một bài (*) về các (*) nếu khách hàng mua hàng tại công ty của Tin. Ai nấy cũng đều (*) cao về (*) của Tin. Đặc biệt, nếu ai (*) (*) sẽ được giảm thêm nữa.",
    words: [
      "grand opening",
      "prepare",
      "brochure",
      "advertise",
      "attract",
      "convenient location",
      "well-attended",
      "special offer",
      "discount",
      "purchase",
      "compare",
      "various",
      "accommodate",
      "those who",
      "free shipping",
      "announce",
      "gather",
      "address",
      "demonstration",
      "benefit",
      "evaluate",
      "speech",
      "apply for",
      "membership",
    ],
  },
  {
    id: "story-3",
    title: "Chuyện ở công ty của Tin",
    content:
      "Hôm nay, Tin (*) một (*) tại (*) của công ty. (*), công ty đang có 1 (*) và 2 (*). Trong cuộc họp này, Tin trình bày (*) và (*) rằng (*) của công ty phải đạt (*) ít nhất 1 triệu đô trong năm nay và sẽ (*) một (*) năm tới. Do vậy, Tin (*) Anna làm (*). Tin rất (*) với Anna về (*) của cô ấy trong buổi (*) vừa rồi. Tin (*) rằng công ty sẽ (*) nếu có Anna (*) sức lực. Nhiệm vụ của Anna không chỉ làm sao để (*) của công ty lên mà còn phải (*) việc tìm ra (*) tốt. Tất nhiên Anna có thể dùng (*) của công ty và nhờ human resources (*) để (*) tìm. Nếu thuận lợi, cuối năm mọi người đều sẽ được tăng (*) và tất nhiên là có (*) để được (*) lên các vị trí khác.",
    words: [
      "hold",
      "meeting",
      "headquarters",
      "Currently",
      "accountant",
      "technician",
      "plan",
      "determine",
      "goal",
      "revenue",
      "establish",
      "branch",
      "designate",
      "head of sales department",
      "impressed",
      "experience",
      "interview",
      "believe",
      "develop",
      "contribute",
      "increase sales",
      "responsible for",
      "supplier",
      "budget",
      "human resources department",
      "support",
      "salary",
      "opportunity",
      "promote",
    ],
  },
  {
    id: "story-4",
    title: "Tình hình không ổn",
    content:
      "Tình hình kinh doanh không tốt. Tin đang kêu gọi mọi người đưa ra những (*) để giúp công ty (*). Các (*) nhìn nhau nhưng không ai có (*) gì cả. Tin (*) sẽ có rất nhiều (*), nhưng nếu không (*) thì công ty càng khó khăn hơn. Nguyên nhân phần lớn đến từ các (*) của công ty (*) bị (*) do các máy móc khi Tin mua về đã (*) khiến khách hàng (*) và họ muốn (*) lại. Một số muốn (*) sản phẩm mới, số khác đòi (*). Giải pháp bây giờ là phải (*) lại các máy móc mới, hiện đại hơn. (*), (*) của máy móc (*) mắc nên việc tìm (*) sao cho giá (*) là việc (*) ngay bây giờ. Tin hi vọng (*) 1 tuần, có thể (*) được tình trạng này của (*).",
    words: [
      "initiative",
      "stay competitive",
      "colleague",
      "opinion",
      "accept",
      "risk",
      "change",
      "product",
      "continuously",
      "defective",
      "outdated",
      "complain",
      "return",
      "replace",
      "refund",
      "invest",
      "However",
      "price",
      "relatively",
      "manufacturer",
      "reasonable",
      "urgent",
      "within",
      "solve",
      "company",
    ],
  },
  {
    id: "story-5",
    title: "Nâng cấp an ninh máy tính ở công ty",
    content:
      "Tin quyết định (*) 20 (*) mới về cho công ty. Nhà cung ứng (*) những máy này sẽ tăng (*) một cách (*) và (*) với những cái (*) hiện tại ở công ty. Ngày mai, (*) sẽ đến và lắp đặt máy tính cũng như (*). Công ty cũng mua thêm (*) để (*) rằng tất cả các (*) quan trọng và (*) không bị mất cắp. Ngay bây giờ, nhân viên cần (*) tất cả (*) quan trọng ra (*) bởi vì ngày mai sẽ không thể (*) máy tính được. Việc làm này sẽ (*) công việc của nhân viên. Sau khi (*) xong, nhân viên cần tham gia buổi (*) hướng dẫn sử dụng và sau đó phải tuân thủ đúng (*). Nếu có bất cứ thắc mắc nào, đừng (*) để (*) phòng (*). (*) sẽ được gửi qua email của mỗi người, khi nhận được, vui lòng (*) là bạn đã nhận được (*).",
    words: [
      "order",
      "computer",
      "guarantee",
      "productivity",
      "considerably",
      "compatible",
      "printer",
      "technician",
      "network",
      "software",
      "make sure",
      "document",
      "confidential",
      "copy",
      "data",
      "disk",
      "access",
      "facilitate",
      "install",
      "training session",
      "process",
      "hesitate",
      "contact",
      "technical support",
      "Detail",
      "reply to",
      "announcement",
    ],
  },
  {
    id: "story-6",
    title: "Tuyển nhân viên",
    content:
      "Vì (*) nhân sự để (*) hoạt động, Tin đang (*) 1 (*). Để (*) (*), các (*) phải tải (*) trên công ty. Các bằng cấp được yêu cầu phải được (*) trong đó. Sau đó, các (*) phải (*) online ngược lại. Để (*) người giỏi, công ty đưa ra (*) cũng rất khắt khe vì muốn (*) 1 người có (*) tốt nhất. (*), bạn phải có 2 năm (*). (*) cao, (*), (*) tốt, đồng thời, nếu làm (*), bạn còn sẽ được (*). Tuy nhiên, có thể bạn phải (*) và (*) (*). \nNếu bạn (*), bạn sẽ được mời tham gia (*). (*), bạn sẽ phải (*) 1 buổi đào tạo (*) 7 ngày để hiểu rõ hơn về công ty và công việc của bạn. Bạn được (*) hợp đồng thử việc 2 tháng và được (*) công việc. Đây là giai đoạn rất quan trọng để bạn (*) (*) của bạn. Nếu bạn không làm tốt, rất tiếc, công ty phải (*) bạn. Sau 2 tháng, bạn được ký (*). Ngoài lương, bạn còn được đóng (*). Cuối năm, công ty sẽ có (*) để chọn ra người có (*) nhất và trao (*).",
    words: [
      "ack of",
      "expand",
      "recruit",
      "supervisor",
      "apply for",
      "position",
      "candidate",
      "application form",
      "enclose/ attach",
      "applicant",
      "submit",
      "hire",
      "requirement",
      "choose",
      "qualification",
      "At least",
      "experience",
      "Salary",
      "negotiable",
      "benefit",
      "work overtime",
      "compensate",
      "relocate",
      "go on business",
      "consistently",
      "eligible",
      "interview",
      "Shortly thereafter",
      "take part in",
      "within",
      "sign",
      "assign",
      "demonstrate",
      "ability",
      "fire",
      "permanent contract",
      "medical corverage",
      "performance review",
      "contribution",
      "award",
    ],
  },
  {
    id: "story-7",
    title: "Quy trình mua hàng ở công ty",
    content:
      "Sản phẩm chất lượng, cùng với các (*) quảng cáo hiệu quả, (*) của công ty Tin càng lớn. (*) ngày càng nhiều nên việc bố trí các (*) sao cho (*) và đảm bảo (*) luôn (*) là điều (*) bây giờ. Khi khách hàng tới cửa hàng tham quan và (*) món hàng cần mua, nhân viên cần phải lịch sự xin tên và số điện thoại để (*) (*). Nếu khách hàng còn đang phân vân thì đưa (*) và (*) khách hàng. Nhân viên phải (*) kỹ trong (*) có còn sản phẩm đó hay không. Nhân viên nhớ (*) khách hàng (*) đúng số điện thoại vì nó sẽ dùng để (*) việc mua hàng trong trường hợp khách hàng làm mất (*). Nếu có bất kỳ (*) nào thì phải sửa ngay. (*) của công ty là tất cả các sản phẩm đều được (*) 1 năm. Nếu sản phẩm có bất kỳ (*) nào, quý khách được (*) lại sảm phẩm mới hoặc được (*) lại. Khách hàng (*) thì sẽ được tính (*), còn không thì phải trả thêm phần (*) (*). Tuỳ thuộc vào khoảng cách mà nhân viên sẽ (*) thời gian giao hàng (*). Thông thường thì khách hàng sẽ (*) sản phẩm (*) vào ngày hôm sau.",
    words: [
      "campaign",
      "reputation",
      "Customer",
      "item",
      "convenient",
      "merchandise",
      "available",
      "crucial",
      "decide",
      "fulfill",
      "order",
      "catalog",
      "consult",
      "check",
      "warehouse",
      "remind",
      "provide",
      "verify",
      "invoice/receipt",
      "mistake",
      "Policy",
      "warranty",
      "defective",
      "replace",
      "refund",
      "buy in bulk",
      "no extra cost",
      "delivery",
      "charge",
      "estimate",
      "accurately",
      "receive",
      "promptly",
    ],
  },
  {
    id: "story-8",
    title: "Đầu tư",
    content:
      "Hôm nay, Tin ghé qua (*) để (*) (*) ngân hàng của công ty để thực hiện các (*) dễ dàng với khách hàng hơn. (*) nói Tin phải cung cấp (*) và điền vào mẫu đơn. Tin đọc (*) các mục rồi sau đó ký (*). Với những (*), bây giờ khách hàng có thể chuyển khoản trực tiếp (*) tài khoản của công ty mà không cần phải đến cửa hàng. Theo như (*) của Tin, việc này sẽ giúp cho bộ phận (*) bớt đi áp lực công việc. Trong lúc ngồi chờ, Tin nghĩ, nếu sau này mình có nhiều tiền, Tin sẽ là 1 (*). Tin sẽ tìm những công ty phát triển ổn định để đầu tư (*). Ngoài ra, Tin cũng sẽ đầu tư vào (*), Tin (*) lựa chọn những (*) gần (*) để dễ cho thuê. Nếu cần, Tin sẽ (*) căn nhà lại cho phù hợp với nhu cầu của khách hàng. Vì có quá nhiều (*) trên thị trường nên Tin phải cung cấp (*) với (*) cho khách hàng, thì mới (*) được nhiều người thuê.",
    words: [
      "bank",
      "activate",
      "account",
      "transaction",
      "Cashier",
      "identification",
      "carefully",
      "signature",
      "outstanding bil",
      "through",
      "forecast",
      "accounting",
      "investor",
      "long-term",
      "real estate",
      "intend to",
      "aparment",
      "public transportation",
      "customize",
      "competitor",
      "excellent service",
      "reasonable price",
      "attract",
    ],
  },
  {
    id: "story-9",
    title: "Đăng ký tạp chí",
    content:
      "(*) TPA là tạp chí (*) về lĩnh vực (*). Tin đã (*) tạp chí này được 2 tháng. Các (*) của nó (*) 2 tuần 1 lần, cung cấp những kiến thức rất bổ ích cho những người mới kinh doanh như Tin. Hôm nay, nhân dịp (*) 10 năm của TPA, nếu ai đăng ký 1 năm sẽ được nhận được (*) giảm 50%. Những ai đăng ký mà đã (*), nếu (*) lại thì được tặng thêm 1 tháng nhận báo miễn phí. Tại buổi lễ, TPA mời đến 1 (*) nổi tiếng, với cuốn sách (*) NHÀ KHỞI NGHIỆP THÔNG MINH. Tại đây, anh sẽ chia sẻ kinh nghiệm xương máu mà anh đã trải qua, từ việc xuất phát điểm là 1 (*), thi đấu thất bại trong 3 năm (*), (*) gặp tai nạn nặng đến mức (*) được (*) cho đến (*) thành công của ngày hôm nay. Bài chia sẻ của anh sẽ (*) trong 30 phút. Sau đó, anh sẽ trả lời những câu hỏi của (*). Cũng trong dịp này, buổi ký tặng sách sẽ được tiến hành. Toàn bộ chi phí sẽ do TPA (*), số tiền thu được từ việc bán sách sẽ được (*) để gây (*). (*) tham gia thì miễn phí. Tuy nhiên, về (*) chỉ có 100 chỗ ngồi nên những ai xác định tham gia nên đăng ký giữ chỗ (*).",
    words: [
      "Magazine",
      "famous",
      "business",
      "subscribe",
      "issue",
      "publish",
      "celebrate",
      "voucher",
      "expire",
      "renew",
      "author",
      "best seller",
      "athlete",
      "consecutive",
      "unfortunately",
      "discontinue",
      "career",
      "achievement",
      "take place",
      "audience",
      "donate",
      "contribute",
      "charity fund",
      "Admission",
      "capacity",
      "in advance",
    ],
  },
  {
    id: "story-10",
    title: "Du lịch công ty",
    content:
      "Sau 6 tháng hoạt động, với sự nỗ lực hết mình, công ty của Tin đã đạt được doanh thu (*). Dưới đây là email của công ty du lịch Apax gửi cho Tin: “Apax là công ty (*) tổ chức du lịch. Hơn 5 năm qua, chúng tôi đã trở thành đơn vị (*) nếu quý công ty muốn tổ chức các (*) gắn kết tập thể công ty. Nếu quý công ty đăng ký (*) thì sẽ được giảm 10% tiền phòng khách sạn. Apax sẽ (*) cho công ty dựa trên số lượng người mà công ty cung cấp. Đồng thời, (*) vào các khu vui chơi sẽ giảm 15%. Đây là (*) chung của công ty, ngay cả trong trường hợp quý khách (*), hãy cứ gửi cho chúng tôi (*), chúng tôi sẽ (*) lên cấp trên. Nếu nhận được (*), chúng tôi sẽ (*) quý khách ngay. Quý khách có thể (*) bằng cách (*) email này hoặc đến trực tiếp (*) của chúng tôi. Tuy nhiên, (*) đang (*) nên quý khách vui lòng đậu xe ở toà nhà bên cạnh. Khi kết thúc tour, chúng tôi sẽ (*) 1 (*). Quý khách sẽ nhận được (*). Chúng tôi luôn lắng nghe (*) của quý khách. Hãy yên tâm vì phản hồi của quý vị sẽ được (*). Xin cảm ơn.”",
    words: [
      "as planned",
      "specialize in",
      "reliable/dependable",
      "outdoor activities",
      "guided tour",
      "make a reservation",
      "ticket",
      "policy",
      "tight budget",
      "proposal",
      "present",
      "approval",
      "notify",
      "register",
      "reply to",
      "office",
      "parking lot",
      "under construction",
      "conduct",
      "survey",
      "questionnaire",
      "feedback",
      "strictly confidential",
    ],
  },
  {
    id: "story-11",
    title: "Mở rộng kinh doanh",
    content:
      "Sau 1 năm ổn định và phát triển, (*) tại (*) đã cũ, Tin quyết định (*) lại. Một số (*) cũng phải mua lại. Việc này có thể gây (*) cho nhân viên. Vì thế, trong tuần này, nhân viên sẽ (*) lịch làm việc của mình, làm trễ hơn và về trễ hơn. Công ty sẽ (*) tiền để (*) nhân viên làm việc. Những người thợ sửa văn phòng sẽ cố gắng hoàn thành (*), hoặc (*). Trường hợp (*) không ai (*) cả, vì nó sẽ phát sinh thêm rất nhiều (*). Sau khi sửa chữa, công ty sẽ (*) các (*) mới, nên hiện tại đang (*) những (*) kể cả trong công ty và bên ngoài để (*). \nỨng viên phải có (*) và (*) sản xuất, có thể (*) và (*) (*). Nhiệm vụ chính là (*) quy trình sản xuất không bị (*). Vị trí này đòi hỏi khả năng làm việc (*) cũng như (*). Đừng lo vì bạn sẽ có cấp trên (*). Tất nhiên, bạn phải (*) hướng dẫn của cấp trên. Nếu bạn đang (*) 1 (*) để phát triển bản thân và nhận thấy mình sẽ là một nhân viên (*) thì đây là vị trí vô cùng phù hợp với bạn. (*), bạn (*) kèm với (*) của bạn và (*) cho công ty.",
    words: [
      "facility",
      "headquarters",
      "renovate",
      "office supplies",
      "interrupt",
      "reschedule",
      "reimburse",
      "encourage",
      "on schedule",
      "ahead of schedule",
      "behind schedule",
      "expect",
      "expense",
      "implement",
      "project",
      "seek",
      "potential individual",
      "fill the vacant position",
      "comprehensive knowledge of",
      "familiarity with",
      "figure out",
      "handle problem",
      "in a timely manner",
      "in charge of",
      "error",
      "collaboratively",
      "independently",
      "instruct",
      "comply with/abide by/ adhere to",
      "look for",
      "opportunity",
      "potential",
      "Simply",
      "fill out a form",
      "résumé",
      "hand in",
    ],
  },
  {
    id: "story-12",
    title: "Ra mắt sản phẩm mới",
    content:
      "Công ty Betin là (*) của Tin (*) 1 (*) để quảng bá về sản phẩm mới nhất cuả họ. Đây là (*) lớn, có đến 10 (*) và (*). Họ còn (*) thêm 5 (*). (*) của công ty đã gọi điện, gửi (*) cho nhiều đối tác, kể cả các đối tác (*). Để việc (*) sản phẩm này thành công, chính (*) của công ty sẽ (*) về (*) của sản phẩm trước các (*) của các công ty tham gia. Sản phẩm này (*) khách hàng tiến hành việc kinh doanh trôi chảy hơn. Chủ tịch (*) sản phẩm sẽ (*) (*) của những công ty tham dự, bởi vì các (*) trước đây đã nhận được rất nhiều (*) (*). Giá sản phẩm cũng (*) hợp lý vì chỉ (*) 1000$. Họ (*) mục tiêu sẽ ký kết được hợp đồng ngay tại ngày hôm đó, vì (*) của hợp đồng họ cũng đã gửi trước đó cho khách hàng tham khảo. Tất nhiên chỉ cần đặt cọc trước, còn (*) đủ thì không nhất thiết.",
    words: [
      "partner",
      "organize",
      "seminar/workshop",
      "event",
      "secretary",
      "receptionist",
      "hire",
      "assistant",
      "Executive",
      "invitation",
      "international",
      "launch/release",
      "president",
      "present",
      "feature",
      "representative",
      "allow",
      "commit",
      "meet/accommodate",
      "need",
      "version",
      "reflect",
      "positive",
      "extremely",
      "approximately",
      "determine",
      "terms and conditions",
      "payment",
    ],
  },
  {
    id: "story-13",
    title: "Hãng hàng không V-Airline",
    content:
      "(*), những người trẻ tuổi (*) du lịch bụi, duy chuyển bằng xe máy tới những (*) mà họ (*) chi trả hơn là các phương tiện cao cấp, (*) là (*) vì giá quá mắc và rất hay bị (*). Hoạt động của hãng hàng không V-Airline cũng bị ảnh hưởng khá nhiều, vì thế công ty (*) ý tưởng chuyển sang kinh doanh vé máy bay giá rẻ để tăng (*) duy chuyển bằng (*). Với chính sách (*), V-Airline đã (*) được những (*) so với đối thủ và nhanh chóng trở thành (*). Với (*) là giá (*), chỉ sau 2 năm hoạt động, V-Airline đã giành được hầu hết (*). Đến nỗi, (*) của công ty cũng vươn ra quốc tế. Việc (*) (*) của hãng sao cho giá luôn rẻ yêu cầu phải (*) rất nhiều. Do vậy mà các (*) cao cấp cũng bị (*). Tuy nhiên, công ty luôn luôn đặt (*) làm (*) của mình.",
    words: [
      "Recently",
      "have a tendency to",
      "destination",
      "capable of",
      "especially",
      "flight",
      "delay/postpone",
      "come up with",
      "demand",
      "plane",
      "reasonable price/rate",
      "obtain",
      "outstanding accomplishment",
      "leading firm",
      "advantage",
      "competitive",
      "market share",
      "reputation",
      "maintain",
      "operation",
      "cut cost",
      "service",
      "restricted",
      "customer satisfaction",
      "priority",
    ],
  },
  {
    id: "story-14",
    title: "Sách dạy nấu ăn",
    content:
      "Nhà hàng Beerant vừa kết hợp với (*) nổi tiếng, ông Michel để tung ra 1 cuốn sách về nấu ăn (*), (*), chưa từng có trên thị trường. Bộ sách vừa được tung ra (*) thì đã có 1000 người đặt mua. Những bà nội trợ (*) sự khác biệt (*) của bộ (*) này so với các quyển sách khác hiện có trên thị trường. Vì nó (*) các bí quyết nấu ăn mà các cuốn sách khác thường dấu diếm. Đầu bếp Michel đã đi vòng quanh thế giới để (*) và (*) các (*) nấu ăn trong 1 năm trước khi viết thành sách. Cuốn sách này giúp người đọc (*) việc lãng phí thời gian và tiền bạc để đăng ký 1 khoá học nấu ăn. (*) của các món ăn (*) nhiều, hướng dẫn khá (*) nên hầu như chỉ cần áp dụng đúng công thức là sẽ có được một (*) (*) ngay. Tát nhiên, ngày ra mắt sách, ông Machel có (*) và làm mẫu một vài món ăn. Ai cũng (*) xem ông thể hiện tài năng của mình. Việc này (*) 1 tiếng (*) 30 phút như dự định.",
    words: [
      "chef",
      "exclusive",
      "unique",
      "officially",
      "recognize",
      "obviously",
      "document",
      "disclose/reveal",
      "assess/evaluate",
      "assemble",
      "recipe",
      "avoid",
      "Variety",
      "relatively",
      "specific",
      "delicious",
      "dish",
      "particiapate in",
      "tobe eager to",
      "last",
      "instead of",
    ],
  },
  {
    id: "story-15",
    title: "Tiệm bánh mỳ nổi tiếng",
    content:
      "Theo cuộc (*) gần đây của local (*), (*) ABC đứng đầu về (*) và đạt được (*) nhiều nhất so với các tiệm bánh khác. Để có được (*) (*), tiệm bánh đã luôn (*) để tạo ra những chiếc bánh (*) nhất. Không những thế, ABC còn có dịch vụ (*) cho (*) đến nỗi bánh tới tay người dùng vẫn còn nóng như vừa mới ra lò. Nếu bánh bị (*) trong quá trình giao, (*) sẽ (*) (*) và (*) đổi bánh mới ngay. Tất cả các nhân viên giao hàng đều có (*) (*). Hiện tại, sắp tới Valentine, ABC đưa ra chương trình ưu đãi, mua từ 5 bánh sẽ được 1 cặp (*) (*) xem (*) vào cuối tuần này. Nếu gia đình có con dưới 5 tuổi thì bé sẽ (*) vé, (*) phải (*) bố mẹ.",
    words: [
      "survey",
      "local community",
      "bakery",
      "popularity",
      "profit",
      "significant",
      "achievement",
      "make efforts",
      "quality",
      "delivery",
      "recipient",
      "damage",
      "staff",
      "immediately",
      "verify",
      "carry out",
      "driver’s license",
      "valid",
      "complimentary",
      "ticket",
      "concert",
      "tobe exempt from",
      "as long as",
      "accompanied by",
    ],
  },
  {
    id: "story-16",
    title: "Thư mời tham gia buổi tiệc",
    content:
      "Nhằm ghi nhận sự (*) của (*), công ty gửi đến toàn bộ nhân viên email lần thứ 2 như là (*) để tham gia buổi tiệc (*) kỷ niệm 10 năm công ty hoạt động. (*) sẽ được (*) ở nhà hàng White Palace, (*) VPT bank. Sau 1 tháng (*) quá trình (*), nhà hàng đã có (*). Đồng thời (*) cũng (*) hơn rất nhiều. Vấn đề bây giờ là bạn phải xác nhận có tham gia hay không để chúng tôi biết chắc (*) của (*) để (*). (*) bạn có tham gia thì cũng phải phản hồi lại email cho chúng tôi. Lưu ý, bữa tiệc này (*) tất cả nhân viên, kể cả nhân viên (*). Bạn sẽ nhận (*) (*) 20 tháng này. Chúng tôi (*) tới tất cả các bạn, và rất hi vọng rằng nhìn thấy các bạn ở ngày hôm đó. \nĐặc biệt, công ty sẽ vinh danh Pak, cũng là người sắp (*) vào tháng tới, người đã gắn bó cùng với công ty 30 năm qua.",
    words: [
      "dedication",
      "employee",
      "reminder",
      "anniversary",
      "Ceremony",
      "hold",
      "adjacent to",
      "undergo",
      "renovation",
      "spacious interior",
      "design",
      "innovate",
      "number",
      "attendee",
      "book table",
      "Whether or not",
      "intend for",
      "temporary",
      "advance ticket",
      "prior to",
      "extend our sincere thanks",
      "retire",
    ],
  },
  {
    id: "story-17",
    title: "Ngày cuối tuần",
    content:
      "Hôm nay là cuối tuần, Tin thật sự muốn đi đâu đó để giảm cằn thẳng vì nguyên cả tuần rồi Tin tin có đến 3 (*) và phải chạy để không bị (*). Tin muốn đi (*), nhưng mà (*) cuối tuần này cũng đang có (*) đến 30% nên Tin đang phân vân. Tin rủ những người bạn của mình thì họ lại muốn đi đến trung tâm thương mại Vincom mới mở. Vì ở đó sẽ có rất nhiều loại hình (*) nên sẽ vui lắm. Tin đồng ý. Để (*) (*) nhiều hơn, Vincon đã treo băng rôn quảng cáo khá lớn và phát (*) trước đó cả tuần. Tới nơi, cả nhóm vô cùng (*) bởi (*) của toà nhà. Từ (*) cho đến đèn trang trí, nội thất,... quá hoàn hảo. Họ quả thật là (*) trong việc chinh phục khách hàng. Đúng là không phụ lòng (*) của khách hàng, cũng không không (*) sai sự thật. Ngày nay, ngoài việc ăn no qua, thì việc mặc đẹp, mặc (*) và (*) có giá (*) là những điều không thể bỏ qua. Tin và bạn đi vào khu vực trò chơi thì may mắn (*) mà nhận được 1 (*) trị giá là 1 (*) 2 ngày 3 đêm lại Đà Lạt, cùng với (*) tất cả bữa ăn. Cả nhóm vô cùng mãn nguyện.",
    words: [
      "project",
      "behind schedule",
      "museum",
      "concert",
      "discount",
      "entertainment",
      "attract",
      "customer",
      "brochure",
      "impressed",
      "design",
      "elevator",
      "expert",
      "expect",
      "advertise",
      "durable",
      "items",
      "reasonable",
      "fill out a form",
      "voucher",
      "vacation",
      "complimentary",
    ],
  },
  {
    id: "story-18",
    title: "Một ngày tồi tệ",
    content:
      "Hôm nay Tin phải go on (*) ở Acex (*). Tin (*) vé máy bay khứ hồi trước đó 2 tuần. Đồng thời cũng đã đặt (*) khách sạn. Khi Tin ra sân bay thì lại nhận được (*) là máy bay bị (*) lại hôm sau mới đi, vì lý do (*). Tin rất lo lắng vì sợ trễ công tác. Tin đổi vé máy bay thì nhân viên hướng dẫn Tin (*) cổng số 7 để làm (*). Khi tới nơi, nhân viên nói rằng (*) tất cả các chuyến bay đều đã được đặt vé sạch. Vậy là không còn (*) nào khác, Tin đành lỡ hội nghị và phải (*) đối tác xin lỗi. Điều này cũng có nghĩa là những (*) Tin (*) sẽ không còn ý nghĩa gì nữa. Tin gọi cho khách sạn xem có lấy lại được tiền không thì (*) cũng không được. Đây là lần thứ 2 (*) Tin đi máy bay hãng này và gặp (*) hoài. Tin (*) về việc có nên bay hãng này nữa hay không.",
    words: [
      "go on business",
      "conference center",
      "book",
      "reservation",
      "announcement",
      "postpone",
      "bad weather",
      "proceed to",
      "procedure",
      "currently",
      "choice",
      "contact",
      "document",
      "prepare",
      "result",
      "consecutive",
      "trouble",
      "consider",
    ],
  },
  {
    id: "story-19",
    title: "Thư mời dự họp",
    content:
      "Anh ngữ Benzen (*) tất cả các khách hàng và nhân viên (*) về việc quan trọng sau đây. Over3 5 năm hoạt động và (*), BenzenEnglish chính thức (*) và được (*) tại Thủ Đức. Lễ khai trương sẽ được take (*) vào đầu tuần sau. Riêng cuối tuần này, các (*) sẽ có 1 cuộc (*) để nắm bắt rõ về vấn đề này. Mong các bạn (*). Không vắng (*). Để đảm bảo cuộc họp (*) và (*), vui lòng đọc kỹ (*) được (*) trong email này. Cuộc họp được (*) trong thời gian kéo dài 30 phút thay vì 1 tiếng (*). (*) của bạn là rất quan trọng, tuy nhiên, cũng nhớ rằng, trong cuộc họp có nhiều thông tin (*) nên vui lòng không (*) ra ngoài. Anh Tin sẽ (*) cuộc họp này nên có gì cần cứ liên hệ anh ấy. Về phía khách hàng, (*) việc tri ân, Benzen sẽ có những (*) xinh xắn vào ngày hôm đó cho các bạn.",
    words: [
      "announce",
      "company",
      "Over",
      "develop",
      "establish",
      "locate",
      "take place",
      "division",
      "meeting",
      "keep an appointment",
      "under any circumstances",
      "brief",
      "productive",
      "detail",
      "attach",
      "expected",
      "as planned",
      "Presence",
      "confidential",
      "disclose",
      "in charge of",
      "as part of",
      "gift",
    ],
  },
  {
    id: "story-20",
    title: "Bộ từ vựng TOEIC độc quyền",
    content:
      "BenzenEnglish vừa tung ra bộ tài liệu học TOEIC kiểu mới, được (*) công phu, (*) và (*) trên (*) hiện nay. Bộ truyện được (*) ra (*) 2 tuần (*). Người học có thể (*) sự khác biệt (*) so với các (*). Chính người sáng lập trung tâm đã giành thời gian (*) khả năng của mình để sáng tạo nên, đồng thời (*) lại cho phù hợp với cách học và (*) của học sinh Việt Nam. Bộ truyện tỉnh lượt phần phiên âm để (*) sự phức tạp, các bạn có thể tìm thấy nguồn tra ở phần hướng dẫn. 20 câu chuyện chứa (*), (*) (*) những từ vựng (*) cho cấp độ 550 TOEIC. Rất hi vọng bộ truyện này sẽ giúp các bạn học từ vựng TOEIC nhanh chóng, dễ thuộc và đạt được kết quả thật tốt.",
    words: [
      "compose",
      "exclusive",
      "unique",
      "market",
      "launch",
      "prior to",
      "as anticipated",
      "figure out",
      "obviously",
      "competitor",
      "contribute",
      "customize",
      "ability",
      "avoid",
      "variety",
      "relatively",
      "sufficient",
      "essential",
    ],
  },
];
