export const ToeicNovel = [
  {
    id: "story-1",
    title: "Khi Tin gặp sếp xin nghỉ làm",
    content:
      "Hôm nay, Tin lên văn phòng gặp sếp xin nghỉ làm. Sếp vô cùng (*) và hỏi vì sao Tin lại (*) như vậy. Tin nói, Tin muốn nghỉ làm để (*) vào (*) riêng của mình. Cứ tưởng Tin sẽ bị phạt vì (*). Bất ngờ thay, sếp không tức giận mà lại (*) và nói sẽ (*) Tin nếu Tin cần. Buổi chiều, Tin đi tìm chủ nhà và (*) hợp đồng thuê nhà. Tin bị (*) phải đóng (*) 6 tháng, tuy nhiên, hiện tại Tin không (*) nên Tin (*) chủ nhà cho thêm 1 ít thời gian. Cuối cùng, 2 (*) cũng (*) và (*). Tin và một số người bạn của mình đang lên (*) về marketing, (*),... Tin biết rằng, (*) là vô cùng quan trọng, (*), Tin đã xem xét việc (*) nhưng vẫn đảm bảo (*) cho (*).",
    words: [
      "surprised",
      "decide",
      "focus",
      "business",
      "breach (the contract)",
      "accept",
      "support",
      "negotiate",
      "obligate",
      "deposit",
      "affordable",
      "convince",
      "party",
      "compromise",
      "sign the contract",
      "strategy",
      "product",
      "customer satisfaction",
      "therefore",
      "lower price",
      "quality",
      "customer",
    ],
    length: 22,
  },
  {
    id: "story-2",
    title: "Ngày khai trương",
    content:
      "Hôm nay là ngày (*), sáng nay Tin dậy sớm để (*) mọi thứ cho đâu vào đấy. 1 tuần trước, Tin đã đi phát (*) khắp nơi, (*) trên internet về buổi lễ hôm nay nên hi vọng sẽ (*) nhiều người. Hơn nữa, với (*) của công ty nên hôm nay có nhiều người (*). Nhân dịp khai trương, công ty đưa ra 1 (*), đó là (*) 30% tất cả các sản phẩm nếu khách hàng (*) trong hôm nay. Bởi vì khách hàng thường luôn (*) giá cả khi mua hàng, Tin đã dự trù nhiều dòng sản phẩm (*) để (*) nhu cầu của khách hàng. Ngoài ra, (*) mua hàng hôm nay sẽ được (*). Công ty (*), mọi người (*) tập trung trước sân khấu, Tin (*) một bài (*) về các (*) nếu khách hàng mua hàng tại công ty của Tin. Ai nấy cũng đều (*) cao về (*) của Tin. Đặc biệt, nếu ai apply (*) (*) sẽ được giảm thêm nữa.",
    words: [
      "grand opening",
      "prepare",
      "brochure",
      "advertise",
      "attract",
      "convenient location",
      "well-attended",
      "special offer",
      "discount",
      "purchase",
      "compare",
      "various",
      "accommodate",
      "those who",
      "free shipping",
      "announce",
      "gather",
      "address",
      "demonstration",
      "benefit",
      "evaluate",
      "speech",
      "apply for",
      "membership",
    ],
    length: 24,
  },
  {
    id: "story-3",
    title: "Chuyện ở công ty của Tin",
    content:
      "Hôm nay, Tin (*) một (*) tại (*) của công ty. (*), công ty đang có 1 (*) và 2 (*). Trong cuộc họp này, Tin trình bày (*) và (*) rằng (*) của công ty phải đạt (*) ít nhất 1 triệu đô trong năm nay và sẽ (*) một (*) năm tới. Do vậy, Tin (*) Anna làm (*). Tin rất (*) với Anna về (*) của cô ấy trong buổi (*) vừa rồi. Tin (*) rằng công ty sẽ (*) nếu có Anna (*) sức lực. Nhiệm vụ của Anna không chỉ làm sao để (*) của công ty lên mà còn phải (*) việc tìm ra (*) tốt. Tất nhiên Anna có thể dùng (*) của công ty và nhờ human resources (*) để (*) tìm. Nếu thuận lợi, cuối năm mọi người đều sẽ được tăng (*) và tất nhiên là có (*) để được (*) lên các vị trí khác.",
    words: [
      "hold",
      "meeting",
      "headquarters",
      "Currently",
      "accountant",
      "technician",
      "plan",
      "determine",
      "goal",
      "revenue",
      "establish",
      "branch",
      "designate",
      "head of sales department",
      "impressed",
      "experience",
      "interview",
      "believe",
      "develop",
      "contribute",
      "increase sales",
      "responsible for",
      "supplier",
      "budget",
      "human resources department",
      "support",
      "salary",
      "opportunity",
      "promote",
    ],
    length: 29,
  },
  {
    id: "story-4",
    title: "Tình hình không ổn",
    content:
      "Tình hình kinh doanh không tốt. Tin đang kêu gọi mọi người đưa ra những (*) để giúp công ty (*). Các (*) nhìn nhau nhưng không ai có (*) gì cả. Tin (*) sẽ có rất nhiều (*), nhưng nếu không (*) thì công ty càng khó khăn hơn. Nguyên nhân phần lớn đến từ các (*) của công ty (*) bị (*) do các máy móc khi Tin mua về đã (*) khiến khách hàng (*) và họ muốn (*) lại. Một số muốn (*) sản phẩm mới, số khác đòi (*). Giải pháp bây giờ là phải (*) lại các máy móc mới, hiện đại hơn. (*), (*) của máy móc (*) mắc nên việc tìm (*) sao cho giá (*) là việc (*) ngay bây giờ. Tin hi vọng (*) 1 tuần, có thể (*) được tình trạng này của (*).",
    words: [
      "initiative",
      "stay competitive",
      "colleague",
      "opinion",
      "accept",
      "risk",
      "change",
      "product",
      "continuously",
      "defective",
      "outdated",
      "complain",
      "return",
      "replace",
      "refund",
      "invest",
      "However",
      "price",
      "relatively",
      "manufacturer",
      "reasonable",
      "urgent",
      "within",
      "solve",
      "company",
    ],
    length: 25,
  },
  {
    id: "story-5",
    title: "Nâng cấp an ninh máy tính ở công ty",
    content:
      "Tin quyết định (*) 20 (*) mới về cho công ty. Nhà cung ứng (*) những máy này sẽ tăng (*) một cách (*) và (*) với những cái (*) hiện tại ở công ty. Ngày mai, (*) sẽ đến và lắp đặt máy tính cũng như (*). Công ty cũng mua thêm (*) để (*) rằng tất cả các (*) quan trọng và (*) không bị mất cắp. Ngay bây giờ, nhân viên cần (*) tất cả (*) quan trọng ra (*) bởi vì ngày mai sẽ không thể (*) máy tính được. Việc làm này sẽ (*) công việc của nhân viên. Sau khi (*) xong, nhân viên cần tham gia buổi (*) hướng dẫn sử dụng và sau đó phải tuân thủ đúng (*). Nếu có bất cứ thắc mắc nào, đừng (*) để (*) phòng (*). (*) sẽ được gửi qua email của mỗi người, khi nhận được, vui lòng (*) là bạn đã nhận được (*).",
    words: [
      "order",
      "computer",
      "guarantee",
      "productivity",
      "considerably",
      "compatible",
      "printer",
      "technician",
      "network",
      "software",
      "make sure",
      "document",
      "confidential",
      "copy",
      "data",
      "disk",
      "access",
      "facilitate",
      "install",
      "training session",
      "process",
      "hesitate",
      "contact",
      "technical support",
      "Detail",
      "reply to",
      "announcement",
    ],
    length: 27,
  },
  {
    id: "story-6",
    title: "Tuyển nhân viên",
    content:
      "Vì (*) nhân sự để (*) hoạt động, Tin đang (*) 1 (*). Để (*) (*), các (*) phải tải (*) trên công ty. Các bằng cấp được yêu cầu phải được (*) trong đó. Sau đó, các (*) phải (*) online ngược lại. Để (*) người giỏi, công ty đưa ra (*) cũng rất khắt khe vì muốn (*) 1 người có (*) tốt nhất. (*), bạn phải có 2 năm (*). (*) cao, (*), (*) tốt, đồng thời, nếu làm (*), bạn còn sẽ được (*). Tuy nhiên, có thể bạn phải (*) và (*) (*). \nNếu bạn (*), bạn sẽ được mời tham gia (*). (*), bạn sẽ phải (*) 1 buổi đào tạo (*) 7 ngày để hiểu rõ hơn về công ty và công việc của bạn. Bạn được (*) hợp đồng thử việc 2 tháng và được (*) công việc. Đây là giai đoạn rất quan trọng để bạn (*) (*) của bạn. Nếu bạn không làm tốt, rất tiếc, công ty phải (*) bạn. Sau 2 tháng, bạn được ký (*). Ngoài lương, bạn còn được đóng (*). Cuối năm, công ty sẽ có (*) để chọn ra người có (*) nhất và trao (*).",
    words: [
      "ack of",
      "expand",
      "recruit",
      "supervisor",
      "apply for",
      "position",
      "candidate",
      "application form",
      "enclose/ attach",
      "applicant",
      "submit",
      "hire",
      "requirement",
      "choose",
      "qualification",
      "At least",
      "experience",
      "Salary",
      "negotiable",
      "benefit",
      "work overtime",
      "compensate",
      "relocate",
      "go on business",
      "consistently",
      "eligible",
      "interview",
      "Shortly thereafter",
      "take part in",
      "within",
      "sign",
      "assign",
      "demonstrate",
      "ability",
      "fire",
      "permanent contract",
      "medical corverage",
      "performance review",
      "contribution",
      "award",
    ],
    length: 40,
  },
  {
    id: "story-7",
    title: "Quy trình mua hàng ở công ty",
    content:
      "Sản phẩm chất lượng, cùng với các (*) quảng cáo hiệu quả, (*) của công ty Tin càng lớn. (*) ngày càng nhiều nên việc bố trí các (*) sao cho (*) và đảm bảo (*) luôn (*) là điều (*) bây giờ. Khi khách hàng tới cửa hàng tham quan và (*) món hàng cần mua, nhân viên cần phải lịch sự xin tên và số điện thoại để (*) (*). Nếu khách hàng còn đang phân vân thì đưa (*) và (*) khách hàng. Nhân viên phải (*) kỹ trong (*) có còn sản phẩm đó hay không. Nhân viên nhớ (*) khách hàng (*) đúng số điện thoại vì nó sẽ dùng để (*) việc mua hàng trong trường hợp khách hàng làm mất (*). Nếu có bất kỳ (*) nào thì phải sửa ngay. (*) của công ty là tất cả các sản phẩm đều được (*) 1 năm. Nếu sản phẩm có bất kỳ (*) nào, quý khách được (*) lại sảm phẩm mới hoặc được (*) lại. Khách hàng (*) thì sẽ được tính (*), còn không thì phải trả thêm phần (*) (*). Tuỳ thuộc vào khoảng cách mà nhân viên sẽ (*) thời gian giao hàng (*). Thông thường thì khách hàng sẽ (*) sản phẩm (*) vào ngày hôm sau.",
    words: [
      "campaign",
      "reputation",
      "Customer",
      "item",
      "convenient",
      "merchandise",
      "available",
      "crucial",
      "decide",
      "fulfill",
      "order",
      "catalog",
      "consult",
      "check",
      "warehouse",
      "remind",
      "provide",
      "verify",
      "invoice/receipt",
      "mistake",
      "Policy",
      "warranty",
      "defective",
      "replace",
      "refund",
      "buy in bulk",
      "no extra cost",
      "delivery",
      "charge",
      "estimate",
      "accurately",
      "receive",
      "promptly",
    ],
    length: 33,
  },
  {
    id: "story-8",
    title: "Đầu tư",
    content:
      "Hôm nay, Tin ghé qua (*) để (*) (*) ngân hàng của công ty để thực hiện các (*) dễ dàng với khách hàng hơn. (*) nói Tin phải cung cấp (*) và điền vào mẫu đơn. Tin đọc (*) các mục rồi sau đó ký (*). Với những (*), bây giờ khách hàng có thể chuyển khoản trực tiếp (*) tài khoản của công ty mà không cần phải đến cửa hàng. Theo như (*) của Tin, việc này sẽ giúp cho bộ phận (*) bớt đi áp lực công việc. Trong lúc ngồi chờ, Tin nghĩ, nếu sau này mình có nhiều tiền, Tin sẽ là 1 (*). Tin sẽ tìm những công ty phát triển ổn định để đầu tư (*). Ngoài ra, Tin cũng sẽ đầu tư vào (*), Tin (*) lựa chọn những (*) gần (*) để dễ cho thuê. Nếu cần, Tin sẽ (*) căn nhà lại cho phù hợp với nhu cầu của khách hàng. Vì có quá nhiều (*) trên thị trường nên Tin phải cung cấp (*) với (*) cho khách hàng, thì mới (*) được nhiều người thuê.",
    words: [
      "bank",
      "activate",
      "account",
      "transaction",
      "Cashier",
      "identification",
      "carefully",
      "signature",
      "outstanding bil",
      "through",
      "forecast",
      "accounting",
      "investor",
      "long-term",
      "real estate",
      "intend to",
      "aparment",
      "public transportation",
      "customize",
      "competitor",
      "excellent service",
      "reasonable price",
      "attract",
    ],
    length: 23,
  },
  {
    id: "story-9",
    title: "Đăng ký tạp chí",
    content:
      "(*) TPA là tạp chí (*) về lĩnh vực (*). Tin đã (*) tạp chí này được 2 tháng. Các (*) của nó (*) 2 tuần 1 lần, cung cấp những kiến thức rất bổ ích cho những người mới kinh doanh như Tin. Hôm nay, nhân dịp (*) 10 năm của TPA, nếu ai đăng ký 1 năm sẽ được nhận được (*) giảm 50%. Những ai đăng ký mà đã (*), nếu (*) lại thì được tặng thêm 1 tháng nhận báo miễn phí. Tại buổi lễ, TPA mời đến 1 (*) nổi tiếng, với cuốn sách (*) NHÀ KHỞI NGHIỆP THÔNG MINH. Tại đây, anh sẽ chia sẻ kinh nghiệm xương máu mà anh đã trải qua, từ việc xuất phát điểm là 1 (*), thi đấu thất bại trong 3 năm (*), (*) gặp tai nạn nặng đến mức (*) được (*) cho đến (*) thành công của ngày hôm nay. Bài chia sẻ của anh sẽ (*) trong 30 phút. Sau đó, anh sẽ trả lời những câu hỏi của (*). Cũng trong dịp này, buổi ký tặng sách sẽ được tiến hành. Toàn bộ chi phí sẽ do TPA (*), số tiền thu được từ việc bán sách sẽ được (*) để gây (*). (*) tham gia thì miễn phí. Tuy nhiên, về (*) chỉ có 100 chỗ ngồi nên những ai xác định tham gia nên đăng ký giữ chỗ (*).",
    words: [
      "Magazine",
      "famous",
      "business",
      "subscribe",
      "issue",
      "publish",
      "celebrate",
      "voucher",
      "expire",
      "renew",
      "author",
      "best seller",
      "athlete",
      "consecutive",
      "unfortunately",
      "discontinue",
      "career",
      "achievement",
      "take place",
      "audience",
      "donate",
      "contribute",
      "charity fund",
      "Admission",
      "capacity",
      "in advance",
    ],
    length: 26,
  },
  {
    id: "story-10",
    title: "Du lịch công ty",
    content:
      "Sau 6 tháng hoạt động, với sự nỗ lực hết mình, công ty của Tin đã đạt được doanh thu (*). Dưới đây là email của công ty du lịch Apax gửi cho Tin: “Apax là công ty (*) tổ chức du lịch. Hơn 5 năm qua, chúng tôi đã trở thành đơn vị (*) nếu quý công ty muốn tổ chức các (*) gắn kết tập thể công ty. Nếu quý công ty đăng ký (*) thì sẽ được giảm 10% tiền phòng khách sạn. Apax sẽ (*) cho công ty dựa trên số lượng người mà công ty cung cấp. Đồng thời, (*) vào các khu vui chơi sẽ giảm 15%. Đây là (*) chung của công ty, ngay cả trong trường hợp quý khách (*), hãy cứ gửi cho chúng tôi (*), chúng tôi sẽ (*) lên cấp trên. Nếu nhận được (*), chúng tôi sẽ (*) quý khách ngay. Quý khách có thể (*) bằng cách (*) email này hoặc đến trực tiếp (*) của chúng tôi. Tuy nhiên, (*) đang (*) nên quý khách vui lòng đậu xe ở toà nhà bên cạnh. Khi kết thúc tour, chúng tôi sẽ (*) 1 (*). Quý khách sẽ nhận được (*). Chúng tôi luôn lắng nghe (*) của quý khách. Hãy yên tâm vì phản hồi của quý vị sẽ được (*). Xin cảm ơn.”",
    words: [
      "as planned",
      "specialize in",
      "reliable/dependable",
      "outdoor activities",
      "guided tour",
      "make a reservation",
      "ticket",
      "policy",
      "tight budget",
      "proposal",
      "present",
      "approval",
      "notify",
      "register",
      "reply to",
      "office",
      "parking lot",
      "under construction",
      "conduct",
      "survey",
      "questionnaire",
      "feedback",
      "strictly confidential",
    ],
    length: 23,
  },
  {
    id: "story-11",
    title: "Mở rộng kinh doanh",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
  {
    id: "story-12",
    title: "Ra mắt sản phẩm mới",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
  {
    id: "story-13",
    title: "Hãng hàng không V-Airline",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
  {
    id: "story-14",
    title: "Sách dạy nấu ăn",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
  {
    id: "story-15",
    title: "Tiệm bánh mỳ nổi tiếng",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
  {
    id: "story-16",
    title: "Thư mời tham gia buổi tiệc",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
  {
    id: "story-17",
    title: "Ngày cuối tuần",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
  {
    id: "story-18",
    title: "Một ngày tồi tệ",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
  {
    id: "story-19",
    title: "Thư mời dự họp",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
  {
    id: "story-20",
    title: "Bộ từ vựng TOEIC độc quyền",
    content: "",
    words: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    length: 1,
  },
];
